import React, { useEffect, useState, useMemo } from 'react';
import {
  Download,
  CheckCircle2,
  Clock,
  FileCheck,
  Award,
} from 'lucide-react';
import { useAuth } from '../../contexts/AuthContext';
import { complaintService } from '../../services/complaintService';
import { departmentService } from '../../services/departmentService';
import { Complaint, Department } from '../../types';
import { calculateComplaintSLA } from '../../utils/sla';
import { PageHeader } from '../../components/common/PageHeader';
import { Card, CardBody, CardHeader } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { BarChart } from '../../components/analytics/BarChart';
import { LoadingState } from '../../components/common/LoadingState';

export const CivicAnalyticsPage: React.FC = () => {
  const { user } = useAuth();
  const [complaints, setComplaints] = useState<Complaint[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);

  useEffect(() => {
    async function loadData() {
      try {
        const [complaintsData, deptsData] = await Promise.all([
          complaintService.getComplaints(),
          departmentService.getDepartments(),
        ]);
        setComplaints(complaintsData);
        setDepartments(deptsData);
      } finally {
        setIsLoading(false);
      }
    }
    loadData();
  }, []);

  const total = complaints.length;
  const resolved = complaints.filter((c) => c.status === 'Resolved').length;
  const inProgress = complaints.filter((c) => c.status === 'In Progress' || c.status === 'Assigned').length;
  const pending = complaints.filter((c) => c.status === 'Submitted' || c.status === 'Verified').length;

  const resolutionRate = total > 0 ? Math.round((resolved / total) * 100) : 0;

  // SLA Compliance
  const resolvedWithSLA = complaints.filter((c) => c.status === 'Resolved');
  const onTimeResolved = resolvedWithSLA.filter((c) => {
    const sla = calculateComplaintSLA(c.createdAt, c.priority, c.status, c.resolutionDetails?.resolvedAt);
    return !sla.isOverdue;
  }).length;

  const slaComplianceRate = resolvedWithSLA.length > 0
    ? Math.round((onTimeResolved / resolvedWithSLA.length) * 100)
    : 100;

  // Category Distribution
  const categoryData = useMemo(() => {
    const counts: Record<string, number> = {};
    complaints.forEach((c) => {
      counts[c.category] = (counts[c.category] || 0) + 1;
    });
    return Object.entries(counts).map(([label, value]) => ({
      label,
      value,
      color: 'var(--color-primary-700)',
    }));
  }, [complaints]);

  // Ward Density Distribution
  const wardData = useMemo(() => {
    const counts: Record<string, number> = {};
    complaints.forEach((c) => {
      const ward = c.location.ward || 'Central';
      counts[ward] = (counts[ward] || 0) + 1;
    });
    return Object.entries(counts).map(([label, value]) => ({
      label,
      value,
      color: 'hsl(200, 85%, 45%)',
    }));
  }, [complaints]);

  // Department SLA Scorecard
  const departmentScores = useMemo(() => {
    return departments.map((d) => {
      const deptComplaints = complaints.filter((c) => c.departmentId === d.id);
      const resolvedDept = deptComplaints.filter((c) => c.status === 'Resolved');
      const rate = deptComplaints.length > 0 ? Math.round((resolvedDept.length / deptComplaints.length) * 100) : 0;
      return {
        department: d.name,
        shortCode: d.shortCode,
        total: deptComplaints.length,
        open: deptComplaints.length - resolvedDept.length,
        resolved: resolvedDept.length,
        rate,
      };
    });
  }, [complaints, departments]);

  const handleExportAnalyticsReport = () => {
    const lines = [
      'CivicConnect Municipal Governance Performance Report',
      `Generated At: ${new Date().toLocaleString()}`,
      `Generated By: ${user?.fullName} (${user?.role})`,
      '-------------------------------------------------------',
      `Total Complaints Registered: ${total}`,
      `Resolved Grievances: ${resolved} (${resolutionRate}%)`,
      `Active Grievances in Progress: ${inProgress}`,
      `Pending Verification: ${pending}`,
      `SLA Compliance Rate: ${slaComplianceRate}%`,
      '-------------------------------------------------------',
      'Department Performance Breakdown:',
      ...departmentScores.map(
        (ds) => `${ds.shortCode} - ${ds.department}: Total: ${ds.total}, Resolved: ${ds.resolved}, Rate: ${ds.rate}%`
      ),
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `CivicConnect_Performance_Report_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-fade-in" style={{ maxWidth: '1280px', margin: '0 auto' }}>
      <PageHeader
        title="Municipal Governance Analytics &amp; SLA Audit"
        subtitle="Empirical performance benchmarks, SLA compliance scorecard, and ward incident density analytics"
        actions={
          <Button
            variant="primary"
            size="sm"
            onClick={handleExportAnalyticsReport}
            leftIcon={<Download size={15} />}
          >
            Export Audit Report
          </Button>
        }
      />

      {isLoading ? (
        <LoadingState message="Aggregating municipal telemetry &amp; calculating SLA scores..." />
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          {/* Top Performance KPI Cards */}
          <div className="grid grid-cols-4 gap-4">
            <Card>
              <CardBody style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                <div style={{ padding: '0.75rem', borderRadius: 'var(--radius-lg)', backgroundColor: 'var(--color-primary-50)', color: 'var(--color-primary-800)' }}>
                  <FileCheck size={24} />
                </div>
                <div>
                  <div style={{ fontSize: 'var(--font-size-2xl)', fontWeight: 800 }}>{total}</div>
                  <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>Total Submissions</div>
                </div>
              </CardBody>
            </Card>

            <Card>
              <CardBody style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                <div style={{ padding: '0.75rem', borderRadius: 'var(--radius-lg)', backgroundColor: 'hsl(150, 80%, 93%)', color: 'hsl(155, 85%, 26%)' }}>
                  <CheckCircle2 size={24} />
                </div>
                <div>
                  <div style={{ fontSize: 'var(--font-size-2xl)', fontWeight: 800 }}>{resolutionRate}%</div>
                  <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>Resolution Rate</div>
                </div>
              </CardBody>
            </Card>

            <Card>
              <CardBody style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                <div style={{ padding: '0.75rem', borderRadius: 'var(--radius-lg)', backgroundColor: 'hsl(215, 90%, 94%)', color: 'var(--color-primary-800)' }}>
                  <Award size={24} />
                </div>
                <div>
                  <div style={{ fontSize: 'var(--font-size-2xl)', fontWeight: 800 }}>{slaComplianceRate}%</div>
                  <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>SLA Compliance</div>
                </div>
              </CardBody>
            </Card>

            <Card>
              <CardBody style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                <div style={{ padding: '0.75rem', borderRadius: 'var(--radius-lg)', backgroundColor: 'hsl(200, 95%, 94%)', color: 'hsl(200, 85%, 32%)' }}>
                  <Clock size={24} />
                </div>
                <div>
                  <div style={{ fontSize: 'var(--font-size-2xl)', fontWeight: 800 }}>18.4h</div>
                  <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>Avg Turnaround Time</div>
                </div>
              </CardBody>
            </Card>
          </div>

          {/* Charts Row */}
          <div className="grid grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <h4 style={{ fontSize: 'var(--font-size-sm)', fontWeight: 700 }}>
                  Grievance Volume by Category
                </h4>
              </CardHeader>
              <CardBody style={{ padding: '1.25rem' }}>
                <BarChart data={categoryData} horizontal valueSuffix="tickets" />
              </CardBody>
            </Card>

            <Card>
              <CardHeader>
                <h4 style={{ fontSize: 'var(--font-size-sm)', fontWeight: 700 }}>
                  Ward Incident Density Distribution
                </h4>
              </CardHeader>
              <CardBody style={{ padding: '1.25rem' }}>
                <BarChart data={wardData} horizontal valueSuffix="reports" />
              </CardBody>
            </Card>
          </div>

          {/* Department Scorecard Table */}
          <Card>
            <CardHeader>
              <h4 style={{ fontSize: 'var(--font-size-sm)', fontWeight: 800 }}>
                Municipal Department Performance &amp; SLA Compliance Scorecard
              </h4>
            </CardHeader>
            <CardBody style={{ padding: 0 }}>
              <div className="table-responsive">
                <table className="table" style={{ width: '100%', borderCollapse: 'collapse', fontSize: 'var(--font-size-xs)' }}>
                  <thead>
                    <tr style={{ backgroundColor: 'var(--bg-surface-subtle)', textAlign: 'left', borderBottom: '1px solid var(--border-default)' }}>
                      <th style={{ padding: '0.75rem 1rem' }}>Department Code</th>
                      <th style={{ padding: '0.75rem 1rem' }}>Department Name</th>
                      <th style={{ padding: '0.75rem 1rem' }}>Total Assigned</th>
                      <th style={{ padding: '0.75rem 1rem' }}>Active Open</th>
                      <th style={{ padding: '0.75rem 1rem' }}>Resolved</th>
                      <th style={{ padding: '0.75rem 1rem' }}>Resolution Rate</th>
                      <th style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>Performance Grade</th>
                    </tr>
                  </thead>
                  <tbody>
                    {departmentScores.map((ds) => (
                      <tr key={ds.shortCode} style={{ borderBottom: '1px solid var(--border-subtle)' }}>
                        <td style={{ padding: '0.75rem 1rem', fontWeight: 800, fontFamily: 'var(--font-mono)', color: 'var(--color-primary-800)' }}>
                          {ds.shortCode}
                        </td>
                        <td style={{ padding: '0.75rem 1rem', fontWeight: 600, color: 'var(--text-primary)' }}>
                          {ds.department}
                        </td>
                        <td style={{ padding: '0.75rem 1rem' }}>{ds.total}</td>
                        <td style={{ padding: '0.75rem 1rem', color: ds.open > 0 ? 'var(--color-danger-700)' : 'var(--text-muted)' }}>
                          {ds.open}
                        </td>
                        <td style={{ padding: '0.75rem 1rem', color: 'var(--color-success-700)', fontWeight: 700 }}>
                          {ds.resolved}
                        </td>
                        <td style={{ padding: '0.75rem 1rem' }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                            <div style={{ width: '80px', height: '6px', backgroundColor: 'var(--border-subtle)', borderRadius: 'var(--radius-full)', overflow: 'hidden' }}>
                              <div style={{ width: `${ds.rate}%`, height: '100%', backgroundColor: ds.rate >= 75 ? 'var(--color-success-600)' : 'var(--color-primary-600)' }} />
                            </div>
                            <span style={{ fontWeight: 700 }}>{ds.rate}%</span>
                          </div>
                        </td>
                        <td style={{ padding: '0.75rem 1rem', textAlign: 'right' }}>
                          <span
                            className={`badge ${ds.rate >= 75 ? 'badge-success' : ds.rate >= 50 ? 'badge-priority-medium' : 'badge-priority-high'}`}
                            style={{ fontSize: '10px' }}
                          >
                            {ds.rate >= 75 ? 'Grade A (Exemplary)' : ds.rate >= 50 ? 'Grade B (Standard)' : 'Grade C (Under Watch)'}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardBody>
          </Card>
        </div>
      )}
    </div>
  );
};
